=== MarimerLLC/cslacontrib/branches/2010.11.001/CodeGenTemplates/CodeSmith/CSLA36/CSharp/CslaProject.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CslaProject" type="projectInfo"/>

	<!-- Project -->
	<xs:complexType name="projectInfo">
		<xs:sequence>
			<xs:element name="ProjectName" type="xs:string"/>
			<xs:element name ="GenerationMethod" type="classGenerationMethod"/>
			<xs:element name="Objects">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Object" type="objectInfo" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
				<xs:unique name="uniqueObjectName">
					<xs:selector xpath="Object"/>
					<xs:field xpath="@Name"/>
				</xs:unique>
				<xs:keyref name="childObjectReference" refer="uniqueObjectName">
					<xs:selector xpath="Object" />
					<xs:field xpath="Relationship/@Child"/>
				</xs:keyref>
				<xs:keyref name="parentObjectReference" refer="uniqueObjectName">
					<xs:selector xpath="Object" />
					<xs:field xpath="Relationship/@Parent"/>
				</xs:keyref>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!-- Object -->
	<xs:complexType name="objectInfo">
		<xs:all>
			<xs:element name="TransactionalType" type="transactionalType" minOccurs="0"/>
			<xs:element name="PropertyAuthorization" type="propertyAccessSecurity" minOccurs="0"/>
			<xs:element name="AuthorizationRules" type="xs:boolean" minOccurs="0"/>
			<xs:element name="Relationship" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="Child" type="xs:token" use="optional"/>
					<xs:attribute name="Parent" type="xs:token" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Properties">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Property" type="propertyInfo" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
				<xs:unique name="uniquePropName">
					<xs:selector xpath="Property"/>
					<xs:field xpath="@Name"/>
				</xs:unique>
			</xs:element>
			<xs:element name="DbCommands" minOccurs="0">
				<xs:complexType >
					<xs:sequence>
						<xs:element name="FetchCommand" type="dbCommand" minOccurs="0"/>
						<xs:element name="InsertCommand" type="dbCommand" minOccurs="0"/>
						<xs:element name="UpdateCommand" type="dbCommand" minOccurs="0"/>
						<xs:element name="DeleteCommand" type="dbCommand" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="DbName" type="xs:token" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute ref="Access" use="optional"/>
		<xs:attribute ref="Name" use="required"/>
		<xs:attribute name="Type" type="stereotype" use="required"/>
		<xs:attribute name="Namespace" type="xs:token" use="optional"/>
		<xs:attribute name="DalNamespace" type="xs:token" use="optional"/>
		<xs:attribute name="Base" type="xs:token" use="optional"/>
		<xs:anyAttribute/>
	</xs:complexType>
	
	<!-- Property -->
	<xs:complexType name="propertyInfo">
		<xs:all>
			<xs:element name="ValidationRules" type="commonValidationRules" minOccurs="0"/>
		</xs:all>
		<xs:attribute ref="Access" use="optional"/>
		<xs:attribute ref="Name" use="required"/>
		<xs:attribute name="Type" type="datatype" use="required"/>
		<xs:attribute name="NativeType" type="datatype" use="optional"/>
		<xs:attribute name="Default" type="xs:string" use="optional"/>
		<xs:attribute name="DbColumnName" type="xs:string" use="optional"/>
		<xs:attribute name="EntitySetName" type="xs:string" use="optional"/>
		<xs:attribute name="IsPrimaryKey" type="xs:boolean" use="optional"/>
		<xs:attribute name="IsIdentity" type="xs:boolean" use="optional"/>
		<xs:attribute name="AllowDbNull" type="xs:boolean" use="optional"/>
		<xs:attribute name="IsFilterKey" type="xs:boolean" use="optional"/>
		<xs:attribute name="IsReadOnly" type="xs:boolean" use="optional"/>
		<xs:attribute name="IsChildCollection" type="xs:boolean" use="optional"/>
		<xs:anyAttribute/>
	</xs:complexType>

	<!-- Attributes -->
	<xs:attribute name="Access" type="accessModifier" default="public"/>
	<xs:attribute name="Name" type="xs:token"/>

	<!-- Simple Types -->
	<xs:simpleType name="classGenerationMethod">
		<xs:restriction base="xs:token">
			<xs:enumeration value="SplitPartial" />
			<xs:enumeration value="SplitBase" />
			<xs:enumeration value="Single" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="stereotype">
		<xs:union memberTypes="rootStereotype childStereotype"/>
	</xs:simpleType>
	<xs:simpleType name="rootStereotype">
		<xs:restriction base="xs:token">
			<xs:enumeration value="EditableRoot"/>
			<xs:enumeration value="EditableRootList"/>
			<xs:enumeration value="ReadOnlyRoot"/>
			<xs:enumeration value="ReadOnlyRootList"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="childStereotype">
		<xs:restriction base="xs:token">
			<xs:enumeration value="EditableChild"/>
			<xs:enumeration value="EditableChildList"/>
			<xs:enumeration value="ReadOnlyChild"/>
			<xs:enumeration value="ReadOnlyChildList"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="accessModifier">
		<xs:restriction base="xs:token">
			<xs:enumeration value="public"/>
			<xs:enumeration value="internal"/>
			<xs:enumeration value="protected"/>
			<xs:enumeration value="private"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="datatype">
		<xs:union memberTypes="primitiveDatatype xs:token"/>
	</xs:simpleType>
	<xs:simpleType name="primitiveDatatype">
		<xs:restriction base="xs:token">
			<xs:enumeration value="short"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="long"/>
			<xs:enumeration value="double"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="byte"/>
			<xs:enumeration value="bool"/>
			<xs:enumeration value="Guid"/>
			<xs:enumeration value="DateTime"/>
			<xs:enumeration value="DateTime?"/>
			<xs:enumeration value="SmartDate"/>
			<xs:enumeration value="Timestamp"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Object options -->
	<xs:simpleType name="transactionalType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="None" />
			<xs:enumeration value="Ado" />
			<xs:enumeration value="EnterpriseService" />
			<xs:enumeration value="TransactionScope" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="propertyAccessSecurity">
		<xs:restriction base="xs:token">
			<xs:enumeration value="None" />
			<xs:enumeration value="Both" />
			<xs:enumeration value="Read" />
			<xs:enumeration value="Write" />
		</xs:restriction>
	</xs:simpleType>
	<!-- validation rules -->
	<xs:complexType name="commonValidationRules">
		<xs:all>
			<xs:element name="StringRequired" minOccurs="0">
				<xs:complexType/>
			</xs:element>
			<xs:element name="StringMaxLength" type="xs:int" minOccurs="0"/>
			<xs:element name="IntegerMinValue" type="xs:int" minOccurs="0"/>
			<xs:element name="IntegerMaxLength" type="xs:int" minOccurs="0"/>
			<xs:element name="GenericsMinValue" type="xs:token" minOccurs="0"/>
			<xs:element name="GenericsMaxValue" type="xs:token" minOccurs="0"/>
			<xs:element name="RegExMatch" minOccurs="0">
				<xs:simpleType>
					<xs:union memberTypes="builtinRegexPattern xs:string" />
				</xs:simpleType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:simpleType name="builtinRegexPattern">
		<xs:restriction base="xs:token">
			<xs:enumeration value="SSN"/>
			<xs:enumeration value="Email"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="dbCommand">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Type" use="optional" default="StoredProcedure">
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="StoredProcedure"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== MarimerLLC/cslacontrib/CodeGenTemplates/CodeSmith/CSLA36/CSharp/MySample.xml
<?xml version="1.0" encoding="UTF-8"?>
<CslaProject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CslaProject.xsd">
	<ProjectName>MyApp.Library</ProjectName>
	<GenerationMethod>SplitPartial</GenerationMethod>
	<Objects>	
		<Object Access="internal" Type="EditableRoot" Name="Project" Namespace="MyApp.Library.Internal" DalNamespace="MyApp.Data">
			<PropertyAuthorization>Write</PropertyAuthorization>
			<TransactionalType>TransactionScope</TransactionalType>
			<AuthorizationRules>false</AuthorizationRules>
			<Properties>
				<Property Name="Id" Type="Guid" DbColumnName="Id" IsPrimaryKey="true"/>
				<Property Name="Name" Type="string" DbColumnName="Name">
					<ValidationRules>
						<StringRequired/>
						<StringMaxLength>50</StringMaxLength>
						<RegExMatch>Email</RegExMatch>
					</ValidationRules>
				</Property>
				<Property Name="Started" Type="SmartDate" NativeType="DateTime?"  DbColumnName="Started">
					<ValidationRules>
						<GenericsMinValue>1/1/2005</GenericsMinValue>
						<RegExMatch>(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d</RegExMatch>
					</ValidationRules>
				</Property>
				<Property Name="Ended" Type="SmartDate" NativeType="DateTime?" DbColumnName="Ended" Default="new SmartDate(false)"/>
				<Property Name="Description" Type="string" DbColumnName="Description"/>
				<Property Name="Resources" Type="ProjectResources" EntitySetName="Assignments" Default="ProjectResources.NewProjectResources()" IsChildCollection="true"/>
				<Property Name="LastChanged" Type="Timestamp" DbColumnName="LastChanged"/>
			</Properties>
			<DbCommands DbName="PTracker">
				<FetchCommand Type="StoredProcedure">Project_Get</FetchCommand>
				<InsertCommand>Project_Insert</InsertCommand>
				<UpdateCommand>Project_Update</UpdateCommand>
				<DeleteCommand>Project_Delete</DeleteCommand>
			</DbCommands>
		</Object>
		<Object Name="ProjectResources" Type="EditableChildList">
			<Properties>
				<Property Name="ResourceId" Type="int" IsPrimaryKey="true" IsIdentity="true"/>
			</Properties>
			<Relationship Child="Resource" Parent="Project"/>
		</Object>
		<Object Name="Resource" Type="EditableChild" Base="MyFramework.ChildBusinessBase">
			<Properties>
				<Property Name="ResourceId" Type="int" DbColumnName="ResourceId" IsPrimaryKey="true" IsIdentity="true"/>
				<Property Name="FirstName" Type="string" DbColumnName="FirstName" IsReadOnly="true"/>
				<Property Name="LastName" Type="string" DbColumnName="LastName" IsReadOnly="true"/>
				<Property Name="Role" Type="int" DbColumnName="Role"/>
			</Properties>
			<Relationship Parent="Project"/>
		</Object>
	</Objects>
</CslaProject>
